version: '3.4'

services:
  emailsenderapi:
    container_name: emailsender.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "2011:80"